services:
  # Web service для Telegram бота
  - type: web
    plan: free
    name: video2post
    env: python
    region: frankfurt
    buildCommand: pip install -r requirements-render.txt
    startCommand: bash start.sh
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: CLAUDE_API_KEY
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TEMP_FOLDER
        value: temp
      - key: OUTPUT_FOLDER
        value: output
    
    # Настройки плана (можно изменить в соответствии с требованиями)
    plan: free 